version: '3.7'

volumes:
  jenkins_home:
  certbot-conf:
  certbot-www:

services:

  nginx:
    build:
      context: ../containers/nginx
    container_name: nectr-nginx
    environment:
      SERVER_NAME: <ex. www.google.com>
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    ports:
      - 80:80
      - 443:443

    jenkins:
      build:
        context: ../containers/jenkins
      container_name: nectr-jenkins
      ports:
        - 8080:8080
        - 50000:50000
        - 50022:50022

      volumes:
        - jenkins_home:/var/jenkins_home

  certbot:
    image: certbot/certbot
    container_name: nectr-certbot-renew-cert
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
