version: '3.7'

volumes:
  certbot-conf:
  certbot-www:

services:
  # Relevant documentation: 
  # - https://github.com/linuxserver/docker-ddclient
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    volumes: $HOME/.config/nectr/ddclient/ddclient.conf:/config/ddclient.conf
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London